productosApp/Models/BodegaContext.cs
using Microsoft.EntityFrameworkCore;
namespace productosApp.Models
{
    public class BodegaContext:DbContext
    {
        public BodegaContext(DbContextOptions<BodegaContext> options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder) 
        {
            modelBuilder.Entity<Categoria>()
                .HasMany(c => c.Productos)
                .WithOne(p => p.Categoria)
                .HasForeignKey(p => p.CategoriaId);
        }


        public DbSet<Categoria> Categories { get; set; }
        public DbSet<Producto> Products { get; set; }
    }
}

productosApp/Models/Categoria.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace productosApp.Models
{
    public class Categoria
    {
        public int Id { get; set; }
        [MaxLength(50,ErrorMessage = "El nombre no debe tener más de 50 carácteres")]
        [MinLength(2, ErrorMessage = "El nombre debe tener por lo menos 2 carácteres")]
        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }
        public List<Producto>? Productos { get; set; }
    }
}

productosApp/Models/ErrorViewModel.cs
namespace productosApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

productosApp/Models/Producto.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
namespace productosApp.Models
{
    public class Producto
    {
        public int Id { get; set; }
        [MaxLength(100,ErrorMessage ="Ingresar 100 o menos carácteres")]
        [MinLength(2, ErrorMessage="Ingresar por lo menos 2 carácteres")]
        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; }
        [Range(1, double.MaxValue, ErrorMessage = "Favor agregar un precio mayor a 0")]
        [RegularExpression(@"^-?\d+(?:[\.,]\d+)?$", ErrorMessage = "El valor ingresado debe ser númerico")]
        [Required(ErrorMessage = "El Precio es obligatorio")]
        [DataType(DataType.Currency,ErrorMessage ="El valor ingresado debe ser un precio")]
        public decimal Precio { get; set; }
        [Display(Name = "Categoría Asociada")]
        [Required(ErrorMessage = "La Categoria es obligatoria")]
        public int CategoriaId { get; set; }
        public Categoria? Categoria { get; set; }
    }
}

productosApp/Models/ProductosContext.cs
using Microsoft.EntityFrameworkCore;
namespace productosApp.Models
{
    public class ProductosContext:DbContext
    {
        public ProductosContext(DbContextOptions<ProductosContext> options) : base(options) { }

        protected override void OnModelCreating(ModelBuilder modelBuilder) 
        {
            modelBuilder.Entity<Categoria>()
                .HasMany(c => c.Productos)
                .WithOne(p => p.Categoria)
                .HasForeignKey(p => p.CategoriaId);
        }

    }
}

productosApp/Controllers/CategoriaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using productosApp.Models;

namespace productosApp.Controllers
{
    public class CategoriaController : Controller
    {
        public BodegaContext context;
        public CategoriaController(BodegaContext context)
        {
            this.context = context;
        }

        public IActionResult Nueva()
        {
            Categoria newCategoria = new Categoria();
            return View(newCategoria);
        }

        public IActionResult Guardar(Categoria categoria)
        {
            if(ModelState.IsValid)
            {
                this.context.Categories.Add(categoria);
                this.context.SaveChanges();
                return RedirectToAction("Lista");
            }
            else
            {
                return View("Nueva",categoria);
            }
        }

        public IActionResult Lista()
        {
            List<Categoria> lista = this.context.Categories.Include(c => c.Productos).ToList();
            return View(lista);
        }
    }
}

productosApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using productosApp.Models;
using System.Diagnostics;

namespace productosApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "Bodega";
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

productosApp/Controllers/ProductoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using productosApp.Models;
namespace productosApp.Controllers
{
    public class ProductoController : Controller
    {
        public BodegaContext context;

        public ProductoController(BodegaContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            List<Producto> products = context.Products.Include(p => p.Categoria).ToList();
            return View(products);
        }

        public IActionResult Create()
        {
            List<Categoria> categories = this.context.Categories.ToList();
            ViewBag.Categories = categories;
            Producto p = new Producto();
            return View(p);
        }

        public IActionResult Save(Producto p)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    this.context.Products.Add(p);
                    this.context.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (Exception e)
                {
                    throw;
                }
            }
            else
            {
                List<Categoria> categories = this.context.Categories.ToList();
                ViewBag.Categories = categories;

                return View("Create", p);//RedirectToAction("Create",p);
            }

        }


    }
}

productosApp/Views/Categoria/Lista.cshtml
@model List<productosApp.Models.Categoria>

<div style="margin:auto" class="col-6">
    <table class="table table-bordered border-primary">
    <thead>
        <th>Nombre</th>
        <th>N° Productos</th>
    </thead>
    <tbody>
            @foreach (var categoria in Model) 
            {
                <tr>
                    <td>@categoria.Nombre</td>
                    @if(categoria.Productos != null)
                    {
                        <td>@categoria.Productos.Count()</td>              
                    }else{
                        <td>Sin productos</td>
                    }
                </tr>
            }
    </tbody>
</table>
</div>

productosApp/Views/Categoria/Nueva.cshtml
@model productosApp.Models.Categoria

<div class="col-6" style="margin:auto">
    @using (Html.BeginForm("Guardar", "Categoria", FormMethod.Post))
    {
        <div class="mb-3 mt-3">
            @Html.LabelFor(Model => Model.Nombre)
            @Html.TextBoxFor(Model => Model.Nombre, new { @class="form-control" })
        </div>
        <div class="mb-3 text-danger">
            @Html.ValidationSummary()
        </div>
       <button type="submit" class="btn btn-primary">Guardar</button>
    }
</div>

productosApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido</h1>
    <p>Este es el proyecto de <b>Bodega</b> para el control de Productos y Categorias</a>.</p>
</div>

productosApp/Views/Producto/Create.cshtml
@model Producto
<div class="col-6" style="margin:auto">
    @using (Html.BeginForm("Save", "Producto", FormMethod.Post))
    {
        <div class="mb-3">
            @Html.LabelFor(l => l.Nombre)
            @Html.TextBoxFor(t => t.Nombre, new {@class="form-control"})
        </div>
        <div class="mb-3">
            @Html.LabelFor(l => l.Precio)
            @Html.TextBoxFor(t => t.Precio, new {@class="form-control"})
        </div>
        @if(ViewBag.Categories == null || ViewBag.Categories.Count == 0)
        {
            <div class="mb-3">
                <h3>No hay registros disponibles de Categorías, genere categorías para asociar a nuevos productos</h3>
            </div>
        }
        else
        {
            <div class="mb-3">
                @Html.LabelFor(l => l.Categoria)
                @Html.DropDownListFor(d => d.CategoriaId,new SelectList(ViewBag.Categories,"Id","Nombre"), new {@class="form-select"})
            </div>
            <div class="mb-3 text-danger">
                @Html.ValidationSummary()
            </div>
            <button class="btn btn-primary" type="submit">Crear</button>
        }
    }
</div>

productosApp/Views/Producto/Index.cshtml
@model List<Producto>
<div class="col-6" style="margin:auto">
    <table class="table table-bordered border-primary">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Nombre</th>
                <th scope="col">Precio</th>
                <th scope="col">Categoría</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var p in Model)
            {
                <tr>
                    <td>@p.Id</td>
                    <td>@p.Nombre</td>
                    <td>@p.Precio.ToString("c2")</td>
                    <td>@p.Categoria.Nombre</td>
                </tr>
            }
        </tbody>
    </table>
</div>

productosApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html class="h-100">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

</head>
<body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-lg bg-info">
        <div class="container-fluid">
            <a class="navbar-brand" asp-controller="Home" asp-action="Index">Bodega</a>

            <div class="container-fluid">
            </div>
                       
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="dropdown">
                <button class="btn btn-info dropdown-toggle border-secondary" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Productos
                </button>
                <ul class="dropdown-menu dropdown-menu-lg-end">
                    <li><a class="dropdown-item" asp-controller="Producto" asp-action="Index">Lista</a></li>
                    <li><a class="dropdown-item" asp-controller="Producto" asp-action="Create">Agregar</a></li>
                </ul>
            </div>
            <div class="dropdown" style="margin-left: 10px">
                <button class="btn btn-info dropdown-toggle border-secondary" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Categorias
                </button>
                <ul class="dropdown-menu dropdown-menu-lg-end">
                    <li><a class="dropdown-item" asp-controller="Categoria" asp-action="Lista">Lista</a></li>
                    <li><a class="dropdown-item" asp-controller="Categoria" asp-action="Nueva">Agregar</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div style="padding: 20px" class="flex-shrink-0">
        @RenderBody()
    </div>
    <footer class="text-center text-lg-start bg-light text-muted mt-auto">
        <!-- Copyright -->
        <div class="text-center p-4" style="background-color: aqua;">
            <ul class="text-reset fw-bold" href="#">CERTAMEN FINAL PROGRAMACION WEB</ul>
           <div>
               <ul class="text-reset fw-bold" href="#">Profesor Gustavo Rebolledo</ul>
           </div>
           <div>
               <ul class="text-reset fw-bold" href="#">Alumnos: Javier Bedoya - Francisco Rodriguez</ul>
           </div>
            
        </div>
        <!-- Copyright -->
    </footer>
    <!-- Footer -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>